var arrLang={
  'en':{
    'en':'',
    'rus':'',
    'click_to_close-1':'click,',
    'click_to_close-2':'to close',
    'click_to_close-3':'',
    'click_to_close-4':'click to close',
    'slide-1-title-2':'Projects that somehow related to science:',
    'slide-1-web-1':'Web application, which solves the problem of simple AI, the so-called. "vacuum cleaner"',
    'slide-1-web-2':'Spectral and cepstral sound analysis for voice identification (publication)',
    'slide-1-web-3':'ASP.NET MVC Voice Biometrics Web Service (client\'s identification by voice)',
    'slide-1-web-4':'C# project for finding keywords in Microsoft Word text documents',
    'slide-1-web-5':'Site for nanotechnology laboratory of ISM NASU',
    'slide-1-web-6':'C# (winforms) + Matlab application of the theory of decision-making for labor force planning in the enterprise',
    'slide-1-title-3':'Technologies I use:',
    'slide-1-techno-1':'C# language',
    'slide-1-techno-2':'Matlab (for mathematical tasks and modeling)',
    'slide-1-techno-3':'EViews (for time series analysis)',

    'slide-2-title-2':'Some Android and web app with java and kolin:',
    'slide-2-web-1':'Website for passing tests (is designed for students and teachers)',
    'slide-2-web-2':'Android app converts the energy of voice into the appropriate color (Beta version)',
    'slide-2-title-3':'Technologies I use:',
    'slide-2-techno-1':'Java',
    'slide-2-techno-2':'Android Studio',
    'slide-2-techno-3':'Kotlin',


    'slide-3-title-2':'I like programming in js, writing web app with html + css:',
    'slide-3-web-1':'Single-page React app',
    'slide-3-web-2':'Pure html, css and js',
    'slide-3-web-3':'ASP.NET MVC Voice Biometrics Web Service (client\'s identification by voice)',
    'slide-3-web-4':'ASP.NET WebAPI RSS reader, simple but comfortable in using',
    'slide-3-web-5':'Site for nanotechnology laboratory of ISM NASU',
    'slide-3-title-3':'Technologies I use:',
    'slide-3-techno-1':'Html5',
    'slide-3-techno-2':'Css3 (Scss, Less)',
    'slide-3-techno-3':'JavaScript (ECMAScript)',
    'slide-3-techno-4':'React (to create interactive UIs)',

    'slide-4-title-2':'Some projects in c #, Asp.Net web API and Asp.Net MVC, desktop applications on WPF and Winforms:',
    'slide-4-web-1':'Asp.Net Core Web API, Entity Framework, SQLite, Angular.js (using DI)',
    'slide-4-web-2':'ASP.NET MVC Voice Biometrics Web Service (client\'s identification by voice)',
    'slide-4-web-3':'ASP.NET WebAPI RSS reader, simple but comfortable in using',
    'slide-4-web-4':'C # (Winforms) project for encrypting text data, as well as Microsoft Office documents using the AES algorithm',
    'slide-4-web-5':'Client-server application (using TcpClient) written in C # using WPF technology',
    'slide-4-web-6':'C # (Winforms) application that allows you to find keywords in Microsoft Office documents',
    'slide-4-web-7':'C # (Winforms) with Password keyboard handwriting',
    'slide-4-title-3':'Technologies I use:',
    'slide-4-techno-1':'Asp.Net (Web API, MVC)',
    'slide-4-techno-2':'C# language',
    'slide-4-techno-3':'(WPF, Winforms)',

    'slide-5-title-1':'Hi, my name is Yaroslav, nice to meet you :)',
    'slide-5-text-2':'purposeful',
    'slide-5-text-4':'disciplined',
    'slide-5-text-5':'I have a bachelor\'s degree in the',
    'iasa':'IASA',
    'kpi':'KPI',
    'ukraine':'(Ukraine)',
    'slide-5-title-2':'Intends to engage in front-end development. I want to work remotely.'
  },
  'rus':{
    'en':'',
    'rus':'',
    'click_to_close-1':'нажмите,',
    'click_to_close-2':'чтобы',
    'click_to_close-3':'закрыть',
    'click_to_close-4':'нажмите чтобы закрыть',
    'slide-1-title-2':'Проекты так или иначе связаны с наукой:',
    'slide-1-web-1':'Веб приложение, которое решает задачу простого ИИ, т.н. "пылесоса"',
    'slide-1-web-2':'Спектральный и кепстральный анализ звука для идентификации голоса (публикация)',
    'slide-1-web-3':'ASP.NET MVC веб сервис Voice Biometrics (идентификация клиента по голосу)',
    'slide-1-web-4':'Ефективний статистичний алгоритм знаходження ключових слів у текстових файлах (публікація)',
    'slide-1-web-5':'Сайт для лаборатории нанотехнологий ISM NASU',
    'slide-1-web-6':'C # (winforms) + Matlab приложение теории принятия решений для планирования рабочей силы на предприятии',
    'slide-1-title-3':'Технологии, которые использую:',
    'slide-1-techno-1':'C# language',
    'slide-1-techno-2':'Matlab (для мат. задач и моделирования)',
    'slide-1-techno-3':'EViews (для анализа временных рядов)',

    'slide-2-title-2':'Мои андроид- и веб- приложения:',
    'slide-2-web-1':'Веб приложение (Java) для создания и прохождения тестов (например, в университете)',
    'slide-2-web-2':'Android приложение преобразует энергию голоса в соответствующий цвет (Бета версия)',
    'slide-2-title-3':'Technologies I use:',
    'slide-2-techno-1':'Java',
    'slide-2-techno-2':'Android Studio',
    'slide-2-techno-3':'Kotlin',

    'slide-3-title-2':'Люблю программировать на js, писать сайты на html+css:',
    'slide-3-web-1':'Одностраничное приложение на React',
    'slide-3-web-2':'Чистые html, css и js',
    'slide-3-web-3':'ASP.NET MVC веб сервис Voice Biometrics (идентификация клиента по голосу)',
    'slide-3-web-4':'ASP.NET Web API RSS reader, простой, но удобный в использовании',
    'slide-3-web-5':'Сайт для лаборатории нанотехнологий ISM NASU',
    'slide-3-title-3':'Технологии, которые использую:',
    'slide-3-techno-1':'Html5',
    'slide-3-techno-2':'Css3 (Scss, Less)',
    'slide-3-techno-3':'JavaScript (ECMAScript)',
    'slide-3-techno-4':'React (to create interactive UIs)',

    'slide-4-title-2':'Проекты на c#, Asp.Net web API и Asp.Net MVC, десктоп приложения на WPF и Winforms:',
    'slide-4-web-1':'Asp.Net Core Web API, Entity Framework, SQLite, Angular.js (с использованием DI)',
    'slide-4-web-2':'ASP.NET MVC веб сервис Voice Biometrics (идентификация клиента по голосу)',
    'slide-4-web-3':'ASP.NET Web API RSS reader, простой, но удобный в использовании',
    'slide-4-web-4':'C# (Winforms) проект для шифрования текстовых данных, а также документов Microsoft Office по алгоритму AES:',
    'slide-4-web-5':'Клиент-серверное приложение (с использованием TcpClient) написанное на C# с помощью технологии WPF',
    'slide-4-web-6':'C# (Winforms) приложение позволяющий находить ключевые слова в документах Microsoft Office',
    'slide-4-web-7':'C# (Winforms) Пароль с клавиатурным почерком',
    'slide-4-title-3':'Технологии, которые использую:',
    'slide-4-techno-1':'Asp.Net (Web API, MVC)',
    'slide-4-techno-2':'C# language',
    'slide-4-techno-3':'(WPF, Winforms)',

    'slide-5-title-1':'Привет, меня зовут Ярослав, приятно познакомиться :)',
    'slide-5-text-2':'целеустремленный',
    'slide-5-text-4':'дисциплинированный',
    'slide-5-text-5':'имею диплом бакалавра',
    'iasa':"ИПСА",
    'kpi':"КПИ",
    'slide-5-title-2':'Намерен заниматься front-end разработкой. При этом работать удаленно :)'
  },

  'ua':{
    'en':'',
    'rus':'',
    'ua':'',
    'click_to_close-1':'натисніть,',
    'click_to_close-2':'щоб',
    'click_to_close-3':'закрити',
    'click_to_close-4':'натисніть, щоб закрити',
    'slide-1-title-2':'Проекти так чи інакше пов\'язані з наукої',
    'slide-1-web-1':'Веб додаток, що вирішує задачу простого ШІ, т.з. "пилесоса"',
    'slide-1-web-2':'Спектральний і кепстральний аналіз звука для ідентифікації голоса (публікація)',
    'slide-1-web-3':'ASP.NET MVC веб сервіс Voice Biometrics (ідентифікація клієнта по голосу)',
    'slide-1-web-4':'Ефективний статистичний алгоритм знаходження ключових слів у текстових файлах (публікація)',
    'slide-1-web-5':'Сайт для лабораторії нанотехнологій ISM NASU',
    'slide-1-web-6':'C # (winforms) + Matlab додаток теорії прийняття рішень для планування робочої сили на підприємстві',
    'slide-1-title-3':'Технології, якими користуюсь:',
    'slide-1-techno-1':'C# language',
    'slide-1-techno-2':'Matlab (для мат. задач та моделювання)',
    'slide-1-techno-3':'EViews (для аналізу чясових рядів)',

    'slide-2-title-2':'Android-, та веб- додатки:',
    'slide-2-web-1':'Веб додаток (Java) для створення (викладачем) та проходження (студентом) тестів онлайн',
    'slide-2-web-2':'Android додаток перетворює енергію голосу у відповідний колір (бета версія)',
    'slide-2-title-3':'Technologies I use:',
    'slide-2-techno-1':'Java',
    'slide-2-techno-2':'Android Studio',
    'slide-2-techno-3':'Kotlin',

    'slide-3-title-2':'Люблю програмувати на js, писати сайти на html+css:',
    'slide-3-web-1':'Односторінковий додаток на React',
    'slide-3-web-2':'Чисті html, css та js',
    'slide-3-web-3':'ASP.NET MVC веб сервіс Voice Biometrics (ідентифікація клієнта по голосу)',
    'slide-3-web-4':'ASP.NET Web API RSS reader, простий, але зручний у використанні',
    'slide-3-web-5':'Сайт для лабораторії нанотехнологій ISM NASU',
    'slide-3-title-3':'Технології, якими користуюсь:',
    'slide-3-techno-1':'Html5',
    'slide-3-techno-2':'Css3 (Scss, Less)',
    'slide-3-techno-3':'JavaScript (ECMAScript)',
    'slide-3-techno-4':'React (to create interactive UIs)',

    'slide-4-title-2':'Додатки на c#, веб додатки на Asp.Net web API та Asp.Net MVC, десктоп додатки на WPF і Winforms:',
    'slide-4-web-1':'Asp.Net Core Web API, Entity Framework, SQLite, Angular.js (з використанням DI)',
    'slide-4-web-2':'ASP.NET MVC веб сервіс Voice Biometrics (ідентифікація клієнта по голосу)',
    'slide-4-web-3':'ASP.NET Web API RSS reader, простий, але зручний у використанні',
    'slide-4-web-4':'C# (Winforms) проект для шифрування текстових даних, а також докумеетів Microsoft Office по алгоритму AES:',
    'slide-4-web-5':'Клиєнт-серверний додаток (з використанням TcpClient) написане на C# за допомогою технології WPF',
    'slide-4-web-6':'C# (Winforms) додаток, що може знаходити ключові слова в документах Microsoft Office',
    'slide-4-web-7':'C# (Winforms) Пароль з клавіатурним почерком',
    'slide-4-title-3':'Технології, які використовую:',
    'slide-4-techno-1':'Asp.Net (Web API, MVC)',
    'slide-4-techno-2':'C# language',
    'slide-4-techno-3':'(WPF, Winforms)',

    'slide-5-title-1':'Привіт, мене звуть Ярослав, приємно познайомитися :)',
    'slide-5-text-2':'цілеспрямований',
    'slide-5-text-4':'дисциплінований',
    'slide-5-text-5':'маю диплом бакалавра',
    'iasa':"ІПСА",
    'kpi':"КПІ",
    'slide-5-title-2':'Маю на меті займатися front-end розробкою. При цьому працювати віддалено:)'
  }
}
var lang='ua';
$(function(){
  $('.translate').click(function(){
lang = $(this).attr('id');

$('.lang').each(function(index, element){
$(this).text(arrLang[lang][$(this).attr('key')]);
})
  })
})
