var arrLang={
  'ua':{
    'en':'',
    'rus':'',
    'ua':'',
    'click_to_close-1':'натисніть,',
    'click_to_close-2':'щоб',
    'click_to_close-3':'закрити',
    'click_to_close-4':'натисніть, щоб закрити',
    'slide-1-title-2':'Проєкти, виконані в університеті:',
    'slide-1-web-1':'Магістерська робота',
    'slide-1-web-2':'Прототип голосової аутентифікації на Python (Github проєкт-2019)',
    'slide-1-web-3':'Python-додаток для знаходження параметрів системи голосової аутентифікації (Github 2019)',
    'slide-1-web-4':'Машинне навчання (python) + голосова біометрія (публікація-2019)',
    'slide-1-web-5':'Машинне навчання (python) + прогнозування успішності стартапів (публикация-2019)',
    'slide-1-web-6':'Ідентифікація голосу (c#) (публікація-2016)',
    'slide-1-title-3':'Технології, якими користувався:',
    'slide-1-techno-1':'Python',
    'slide-1-techno-2':'Scikit learn',
    'slide-1-techno-3':'Бібліотека python_speech_features',

    'slide-2-title-2':'Android-, та веб- додатки:',
    'slide-2-web-1':'Java + PostgreSQL веб додаток створений в університеті',
    'slide-2-web-2':'Android додаток перетворює енергію голосу у відповідний колір (2018, зараз видалений з Google Play)',
    'slide-2-title-3':'Technologies I used:',
    'slide-2-techno-1':'Java',
    'slide-2-techno-2':'Android Studio',
    'slide-2-techno-3':'Kotlin',

    'slide-3-title-2':'Проєкти, побудовані, з використанням html + css + js + Next.js (React):',
    'slide-3-web-1':'Написаний з нуля інтернет магазин на Next.js (Seo-оптимізований React)',
    'slide-3-web-2':'Веб-камери світу онлайн (React)',
    'slide-3-web-3':'Задача Штучного інтелекту про пилосос',
    'slide-3-web-4':'Веб-прототип ідентифікації по голосу',
    'slide-3-web-5':'RSS reader для читання новин',
    'slide-3-web-6':'Сайт для лабораторії нанотехнологій ISM NASU',
    'slide-3-title-3':'Технології, якими користуюсь:',
    'slide-3-techno-1':'Html5',
    'slide-3-techno-2':'Css3 (Scss)',
    'slide-3-techno-3':'JavaScript',
    'slide-3-techno-4':'Next.js (SEO - оптимізований React)',

    'slide-4-title-2':'Додатки на c#, веб додатки на Asp.Net web API та Asp.Net MVC, десктоп додатки на WPF і Winforms:',
    'slide-4-web-1':'ASP.NET MVC прототип ідентифікації по голосу (2018)',
    'slide-4-web-2':'ASP.NET Web API Rss reader новин (2018)',
    'slide-4-web-3':'C# (Winforms) проект для шифрування текстових даних, а також докумеетів Microsoft Office по алгоритму AES:',
    'slide-4-web-4':'Клиєнт-серверний додаток (з використанням TcpClient) написане на C# за допомогою технології WPF',
    'slide-4-web-5':'C# (Winforms) додаток, що може знаходити ключові слова в документах Microsoft Office',
    'slide-4-web-6':'C# (Winforms) Пароль з клавіатурним почерком',
    'slide-4-title-3':'Технології, якими користувався:',
    'slide-4-techno-1':'Asp.Net (Web API, MVC)',
    'slide-4-techno-2':'C# language',
    'slide-4-techno-3':'(WPF, Winforms)',

    'slide-5-title-1':'Основні фішки створеного з нуля інтернет магазину Helix:',
    'slide-5-web-1':'Власне посилання (натисніть на картинку) на інтернет магазин',
    'slide-5-web-2':'Створений на Next.js (SEO - оптимізованому React).',
    'slide-5-web-3':'SSG (Static Site Generation) + SSR (Server-Side Rendering) - браузер бачить сайт із відключеним js - це для SEO',
    'slide-5-web-4':'Dashboard для адміністратора з можливістю роботи з товарами, новими замовленнями, блогом, прибутком і т.д.',
  },
  'rus':{
    'en':'',
    'rus':'',
    'click_to_close-1':'нажмите,',
    'click_to_close-2':'чтобы',
    'click_to_close-3':'закрыть',
    'click_to_close-4':'нажмите чтобы закрыть',
    'slide-1-title-2':'Проекты, выполненные в университете:',
    'slide-1-web-1':'Магистерская работа',
    'slide-1-web-2':'Голосовая аутентификация на Python (Github-проект-2019)',
    'slide-1-web-3':'Python-приложение для нахождения параметров системы голосовой аутентификации (Github-2019)',
    'slide-1-web-4':'Машинное обучение (python) + голосовая биометрия (публикация-2019)',
    'slide-1-web-5':'Машинное обучение (python) + прогнозирования успешности стартапов (публикация-2019)',
    'slide-1-web-6':'Идентификация голоса (c#) (публикация-2016)',
    'slide-1-title-3':'Технологии, которыми пользовался:',
    'slide-1-techno-1':'Python',
    'slide-1-techno-2':'Scikit learn',
    'slide-1-techno-3':'Библиотека python_speech_features',

    'slide-2-title-2':'Мои андроид- и веб- приложения:',
    'slide-2-web-1':'Java + PostgreSQL веб приложение созданное в университете',
    'slide-2-web-2':'Android приложение преобразует энергию голоса в соответствующий цвет (2018, сейчас удалено с Google Play)',
    'slide-2-title-3':'Технологии, которыми пользовался:',
    'slide-2-techno-1':'Java',
    'slide-2-techno-2':'Android Studio',
    'slide-2-techno-3':'Kotlin',

    'slide-3-title-2':'Проекты, написанные, с использованием html + css + js + Next.js (React):',
    'slide-3-web-1':'Написанный с нуля интернет магазин на Next.js (Seo-оптимизированный React)',
    'slide-3-web-2':'Веб-камеры мира онлайн (React)',
    'slide-3-web-3':'Задача Искусственного интеллекта про пылесос',
    'slide-3-web-4':'Веб-прототип идентификации по голосу',
    'slide-3-web-5':'Простой RSS reader для чтения новостей',
    'slide-3-web-6':'Сайт для лаборатории нанотехнологий ISM NASU',
    'slide-3-title-3':'Технологии, которые использую:',
    'slide-3-techno-1':'Html5',
    'slide-3-techno-2':'Css3 (Scss)',
    'slide-3-techno-3':'JavaScript',
    'slide-3-techno-4':'Next.js (SEO - оптимизированный React)',

    'slide-4-title-2':'Проекты на c#, Asp.Net web API и Asp.Net MVC, десктоп приложения на WPF и Winforms:',
    'slide-4-web-1':'ASP.NET MVC прототип идентификации по голосу (2018)',
    'slide-4-web-2':'ASP.NET Web API RSS reader, простой, но удобный в использовании',
    'slide-4-web-3':'C# (Winforms) проект для шифрования текстовых данных, а также документов Microsoft Office по алгоритму AES:',
    'slide-4-web-4':'Клиент-серверное приложение (с использованием TcpClient) написанное на C# с помощью технологии WPF',
    'slide-4-web-5':'C# (Winforms) приложение позволяющий находить ключевые слова в документах Microsoft Office',
    'slide-4-web-6':'C# (Winforms) Пароль с клавиатурным почерком',
    'slide-4-title-3':'Технологии, которыми пользовался:',
    'slide-4-techno-1':'Asp.Net (Web API, MVC)',
    'slide-4-techno-2':'C# language',
    'slide-4-techno-3':'(WPF, Winforms)',

    'slide-5-title-1':'Основные фишки созданного с нуля интернет магазина Helix:',
    
  },
  'en':{
    'en':'',
    'rus':'',
    'click_to_close-1':'click,',
    'click_to_close-2':'to close',
    'click_to_close-3':'',
    'click_to_close-4':'click to close',
    'slide-1-title-2':'Projects implemented at the university:',
    'slide-1-web-1':'Master\'s thesis',
    'slide-1-web-2':'Voice authentication in Python (Github project-2019)',
    'slide-1-web-3':'Python-application for finding the parameters of the voice authentication system (Github-2019)',
    'slide-1-web-4':'Machine learning (python) + voice biometrics (publication-2019)',
    'slide-1-web-5':'Machine learning (python) + prediction the success of startups (publication-2019)',
    'slide-1-web-6':'Voice identification (c#) (publication-2016)',
    'slide-1-title-3':'Technologies I used:',
    'slide-1-techno-1':'Python',
    'slide-1-techno-2':'Scikit learn',
    'slide-1-techno-3':'Python_speech_features lib',

    'slide-2-title-2':'Some Android and web app with java and kolin:',
    'slide-2-web-1':'Java + PostgreSQL web application created at the university',
    'slide-2-web-2':'Android app converts the energy of voice into the appropriate color (2018, is deleted from Google Play now)',
    'slide-2-title-3':'Technologies I use:',
    'slide-2-techno-1':'Java',
    'slide-2-techno-2':'Android Studio',
    'slide-2-techno-3':'Kotlin',


    'slide-3-title-2':'Projects written with html + css + js + Next.js (React):',
    'slide-3-web-1':'Written from scratch internet-shop on Next.js (Seo-optimized React)',
    'slide-3-web-2':'World webcams online (React)',
    'slide-3-web-3':'Vacuum cleaner AI (Artificial intelligence) problem',
    'slide-3-web-4':'Web-prototype of identification by voice',
    'slide-3-web-5':'Simple news RSS reader',
    'slide-3-web-6':'Site for nanotechnology laboratory of ISM NASU',
    'slide-3-title-3':'Technologies I use:',
    'slide-3-techno-1':'Html5',
    'slide-3-techno-2':'Css3 (Scss)',
    'slide-3-techno-3':'JavaScript',
    'slide-3-techno-4':'Next.js (SEO - optimized React)',

    'slide-4-title-2':'Some projects in c #, Asp.Net web API and Asp.Net MVC, desktop applications on WPF and Winforms:',
    'slide-4-web-1':'ASP.NET MVC identification by voice prototype (2018)',
    'slide-4-web-2':'ASP.NET WebAPI RSS reader, simple but comfortable in using',
    'slide-4-web-3':'C # (Winforms) project for encrypting text data, as well as Microsoft Office documents using the AES algorithm',
    'slide-4-web-4':'Client-server application (using TcpClient) written in C # using WPF technology',
    'slide-4-web-5':'C # (Winforms) application that allows you to find keywords in Microsoft Office documents',
    'slide-4-web-6':'C # (Winforms) with Password keyboard handwriting',
    'slide-4-title-3':'Technologies, that I used:',
    'slide-4-techno-1':'Asp.Net (Web API, MVC)',
    'slide-4-techno-2':'C# language',
    'slide-4-techno-3':'(WPF, Winforms)',

    'slide-5-title-1':'The main features of the online store created from scratch and named Helix:',
    'slide-5-web-1':'Власне посилання на інтернет магазин',
  }
}
var lang='ua';
$(function(){
  $('.translate').click(function(){
lang = $(this).attr('id');

$('.lang').each(function(index, element){
$(this).text(arrLang[lang][$(this).attr('key')]);
})
  })
})
