var arrLang={
  'en':{
    'en':'',
    'rus':'',
    'click_to_close-1':'click,',
    'click_to_close-2':'to close',
    'click_to_close-3':'',
    'click_to_close-4':'click to close',
    'slide-1-title-2':'Projects that somehow related to science:',
    'slide-1-web-1':'Master\'s thesis',
    'slide-1-web-2':'Voice authentication in Python (Github project-2019)',
    'slide-1-web-3':'Python-application for finding the parameters of the voice authentication system (Github-2019)',
    'slide-1-web-4':'Comparison of the effectiveness of machine learning classifiers in the context of voice biometrics (publication-2019)',
    'slide-1-web-5':'Research and prediction of the startups’ success on kickstarter platform (publication-2019)',
    'slide-1-web-6':'Spectral and cepstral sound analysis for voice identification (publication-2016)',
    'slide-1-title-3':'Technologies I use:',
    'slide-1-techno-1':'Python',
    'slide-1-techno-2':'Scikit learn',
    'slide-1-techno-3':'Python_speech_features lib',

    'slide-2-title-2':'Some Android and web app with java and kolin:',
    'slide-2-web-1':'Website for passing tests (is designed for students and teachers)',
    'slide-2-web-2':'Android app converts the energy of voice into the appropriate color (Beta version)',
    'slide-2-title-3':'Technologies I use:',
    'slide-2-techno-1':'Java',
    'slide-2-techno-2':'Android Studio',
    'slide-2-techno-3':'Kotlin',


    'slide-3-title-2':'I like programming in js, writing web app with html + css:',
    'slide-3-web-1':'Single-page React app',
    'slide-3-web-2':'Pure html, css and js',
    'slide-3-web-3':'ASP.NET MVC Voice Biometrics Web Service (client\'s identification by voice)',
    'slide-3-web-4':'ASP.NET WebAPI RSS reader, simple but comfortable in using',
    'slide-3-web-5':'Site for nanotechnology laboratory of ISM NASU',
    'slide-3-title-3':'Technologies I use:',
    'slide-3-techno-1':'Html5',
    'slide-3-techno-2':'Css3 (Scss, Less)',
    'slide-3-techno-3':'JavaScript (ECMAScript)',
    'slide-3-techno-4':'React (to create interactive UIs)',

    'slide-4-title-2':'Some projects in c #, Asp.Net web API and Asp.Net MVC, desktop applications on WPF and Winforms:',
    'slide-4-web-1':'Asp.Net Core Web API, Entity Framework, SQLite, Angular.js (using DI)',
    'slide-4-web-2':'ASP.NET MVC Voice Biometrics Web Service (client\'s identification by voice)',
    'slide-4-web-3':'ASP.NET WebAPI RSS reader, simple but comfortable in using',
    'slide-4-web-4':'C # (Winforms) project for encrypting text data, as well as Microsoft Office documents using the AES algorithm',
    'slide-4-web-5':'Client-server application (using TcpClient) written in C # using WPF technology',
    'slide-4-web-6':'C # (Winforms) application that allows you to find keywords in Microsoft Office documents',
    'slide-4-web-7':'C # (Winforms) with Password keyboard handwriting',
    'slide-4-title-3':'Technologies I use:',
    'slide-4-techno-1':'Asp.Net (Web API, MVC)',
    'slide-4-techno-2':'C# language',
    'slide-4-techno-3':'(WPF, Winforms)',

    'slide-5-title-1':'Hi, my name is Yaroslav, nice to meet you :)',
    'slide-5-text-4':'I have a bachelor\'s degree in the',
    'iasa':'IASA',
    'kpi':'KPI',
    'ukraine':'(Ukraine)',
  },
  'rus':{
    'en':'',
    'rus':'',
    'click_to_close-1':'нажмите,',
    'click_to_close-2':'чтобы',
    'click_to_close-3':'закрыть',
    'click_to_close-4':'нажмите чтобы закрыть',
    'slide-1-title-2':'Проекты так или иначе связаны с наукой:',
    'slide-1-web-1':'Магистерская работа',
    'slide-1-web-2':'Голосовая аутентификация на Python (Github-проект-2019)',
    'slide-1-web-3':'Python-приложение для нахождения параметров системы голосовой аутентификации (Github-2019)',
    'slide-1-web-4':'Сравнение эффективности классификаторов машинного обучения в контексте голосовой биометрии (публикация-2019)',
    'slide-1-web-5':'Исследование и прогнозирование успешности стартапов платформы kickstarter (публикация-2019)',
    'slide-1-web-6':'Спектральный и кепстральный анализ звука для идентификации голоса (публикация-2016)',
    'slide-1-title-3':'Технологии, которые использую:',
    'slide-1-techno-1':'Python',
    'slide-1-techno-2':'Scikit learn',
    'slide-1-techno-3':'Библиотека python_speech_features',

    'slide-2-title-2':'Мои андроид- и веб- приложения:',
    'slide-2-web-1':'Веб приложение (Java) для создания и прохождения тестов (например, в университете)',
    'slide-2-web-2':'Android приложение преобразует энергию голоса в соответствующий цвет (Бета версия)',
    'slide-2-title-3':'Technologies I use:',
    'slide-2-techno-1':'Java',
    'slide-2-techno-2':'Android Studio',
    'slide-2-techno-3':'Kotlin',

    'slide-3-title-2':'Люблю программировать на js, писать сайты на html+css:',
    'slide-3-web-1':'Одностраничное приложение на React',
    'slide-3-web-2':'Чистые html, css и js',
    'slide-3-web-3':'ASP.NET MVC веб сервис Voice Biometrics (идентификация клиента по голосу)',
    'slide-3-web-4':'ASP.NET Web API RSS reader, простой, но удобный в использовании',
    'slide-3-web-5':'Сайт для лаборатории нанотехнологий ISM NASU',
    'slide-3-title-3':'Технологии, которые использую:',
    'slide-3-techno-1':'Html5',
    'slide-3-techno-2':'Css3 (Scss, Less)',
    'slide-3-techno-3':'JavaScript (ECMAScript)',
    'slide-3-techno-4':'React (to create interactive UIs)',

    'slide-4-title-2':'Проекты на c#, Asp.Net web API и Asp.Net MVC, десктоп приложения на WPF и Winforms:',
    'slide-4-web-1':'Asp.Net Core Web API, Entity Framework, SQLite, Angular.js (с использованием DI)',
    'slide-4-web-2':'ASP.NET MVC веб сервис Voice Biometrics (идентификация клиента по голосу)',
    'slide-4-web-3':'ASP.NET Web API RSS reader, простой, но удобный в использовании',
    'slide-4-web-4':'C# (Winforms) проект для шифрования текстовых данных, а также документов Microsoft Office по алгоритму AES:',
    'slide-4-web-5':'Клиент-серверное приложение (с использованием TcpClient) написанное на C# с помощью технологии WPF',
    'slide-4-web-6':'C# (Winforms) приложение позволяющий находить ключевые слова в документах Microsoft Office',
    'slide-4-web-7':'C# (Winforms) Пароль с клавиатурным почерком',
    'slide-4-title-3':'Технологии, которые использую:',
    'slide-4-techno-1':'Asp.Net (Web API, MVC)',
    'slide-4-techno-2':'C# language',
    'slide-4-techno-3':'(WPF, Winforms)',

    'slide-5-title-1':'Привет, меня зовут Ярослав, приятно познакомиться :)',
    'slide-5-text-4':'имею диплом бакалавра',
    'iasa':"ИПСА",
    'kpi':"КПИ",
  },

  'ua':{
    'en':'',
    'rus':'',
    'ua':'',
    'click_to_close-1':'натисніть,',
    'click_to_close-2':'щоб',
    'click_to_close-3':'закрити',
    'click_to_close-4':'натисніть, щоб закрити',
    'slide-1-title-2':'Проєкти пов\'язані з навчанням в університеті:',
    'slide-1-web-1':'Магістерська робота',
    'slide-1-web-2':'Прототип голосової аутентифікації на Python (Github проєкт-2019)',
    'slide-1-web-3':'Python-додаток для знаходження параметрів системи голосової аутентифікації (Github 2019)',
    'slide-1-web-4':'Порівняння ефективності класифікаторів машинного навчання у контексті голосової біометрії (публікація-2019)',
    'slide-1-web-5':'Дослідження і прогнозування успішності стартапів платформи kickstarter (публікація-2019)',
    'slide-1-web-6':'Спектральний і кепстральний аналіз звука для ідентифікації голоса (публікація-2016)',
    'slide-1-title-3':'Технології, якими користуюсь:',
    'slide-1-techno-1':'Python',
    'slide-1-techno-2':'Scikit learn',
    'slide-1-techno-3':'Бібліотека python_speech_features',

    'slide-2-title-2':'Android-, та веб- додатки:',
    'slide-2-web-1':'Веб додаток (Java) для створення (викладачем) та проходження (студентом) тестів онлайн',
    'slide-2-web-2':'Android додаток перетворює енергію голосу у відповідний колір (бета версія)',
    'slide-2-title-3':'Technologies I use:',
    'slide-2-techno-1':'Java',
    'slide-2-techno-2':'Android Studio',
    'slide-2-techno-3':'Kotlin',

    'slide-3-title-2':'Люблю програмувати на js, писати сайти на html+css:',
    'slide-3-web-1':'Односторінковий додаток на React',
    'slide-3-web-2':'Чисті html, css та js',
    'slide-3-web-3':'ASP.NET MVC веб сервіс Voice Biometrics (ідентифікація клієнта по голосу)',
    'slide-3-web-4':'ASP.NET Web API RSS reader, простий, але зручний у використанні',
    'slide-3-web-5':'Сайт для лабораторії нанотехнологій ISM NASU',
    'slide-3-title-3':'Технології, якими користуюсь:',
    'slide-3-techno-1':'Html5',
    'slide-3-techno-2':'Css3 (Scss, Less)',
    'slide-3-techno-3':'JavaScript (ECMAScript)',
    'slide-3-techno-4':'React (to create interactive UIs)',

    'slide-4-title-2':'Додатки на c#, веб додатки на Asp.Net web API та Asp.Net MVC, десктоп додатки на WPF і Winforms:',
    'slide-4-web-1':'Asp.Net Core Web API, Entity Framework, SQLite, Angular.js (з використанням DI)',
    'slide-4-web-2':'ASP.NET MVC веб сервіс Voice Biometrics (ідентифікація клієнта по голосу)',
    'slide-4-web-3':'ASP.NET Web API RSS reader, простий, але зручний у використанні',
    'slide-4-web-4':'C# (Winforms) проект для шифрування текстових даних, а також докумеетів Microsoft Office по алгоритму AES:',
    'slide-4-web-5':'Клиєнт-серверний додаток (з використанням TcpClient) написане на C# за допомогою технології WPF',
    'slide-4-web-6':'C# (Winforms) додаток, що може знаходити ключові слова в документах Microsoft Office',
    'slide-4-web-7':'C# (Winforms) Пароль з клавіатурним почерком',
    'slide-4-title-3':'Технології, які використовую:',
    'slide-4-techno-1':'Asp.Net (Web API, MVC)',
    'slide-4-techno-2':'C# language',
    'slide-4-techno-3':'(WPF, Winforms)',

    'slide-5-title-1':'Привіт, мене звуть Ярослав, приємно познайомитися :)',
    'slide-5-text-4':'маю диплом магістра',
    'iasa':"ІПСА",
    'kpi':"КПІ",
  }
}
var lang='ua';
$(function(){
  $('.translate').click(function(){
lang = $(this).attr('id');

$('.lang').each(function(index, element){
$(this).text(arrLang[lang][$(this).attr('key')]);
})
  })
})
